name: Node CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.18.0'
        cache: 'npm'

    - name: Build
      run: |
        node --version
        npm install
        npm run build

    -   name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
            message: "Updated documentation and images."
            add: "."
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    -   name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./docs
